substitutions:
  name: waterfurnace
  friendly_name: WaterFurnace Aurora
  component_source: github://espforge/esphome-waterfurnace@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: espforge.waterfurnace
    version: "0.0.1-beta"
  on_boot:
    priority: 800.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

preferences:
  flash_write_interval: 24h

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:

api:
  custom_services: true

ota:
  - platform: esphome
    id: ota_esphome

web_server:
  version: 3
  local: true
  sorting_groups:
    - id: group_thermostat
      name: "Thermostat"
      sorting_weight: 10
    - id: group_axb_performance
      name: "AXB Performance"
      sorting_weight: 20
    - id: group_power
      name: "Power & Electrical"
      sorting_weight: 30
    - id: group_system_outputs
      name: "System Outputs"
      sorting_weight: 40
    - id: group_vs_drive
      name: "VS Drive"
      sorting_weight: 50
    - id: group_vs_sensors
      name: "VS Drive Sensors"
      sorting_weight: 55
    - id: group_controls
      name: "Controls"
      sorting_weight: 60
    - id: group_diagnostics
      name: "Diagnostics"
      sorting_weight: 70

external_components:
  - source: ${component_source}

# RS-485 UART - Waveshare ESP32-S3-RS485-CAN board
# TX: GPIO17, RX: GPIO18, DE: GPIO21 (hardware auto-direction)
uart:
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 19200
  parity: EVEN
  rx_buffer_size: 512

waterfurnace:
  id: wf
  update_interval: 10s
  # flow_control_pin: GPIO21  # Uncomment if hardware auto-direction doesn't work
  connected:
    name: "Connected"
    web_server:
      sorting_group_id: group_thermostat
      sorting_weight: 0
  connected_timeout: 30s

sensor:
  - platform: waterfurnace
    # --- Thermostat ---
    ambient_temperature:
      name: "Ambient Temperature"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 10
    outdoor_temperature:
      name: "Outdoor Temperature"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 20
    entering_air_temperature:
      name: "Entering Air Temperature"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 30
    relative_humidity:
      name: "Relative Humidity"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 40
    # --- AXB Performance ---
    entering_water_temperature:
      name: "Entering Water Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 10
    leaving_water_temperature:
      name: "Leaving Water Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 20
    leaving_air_temperature:
      name: "Leaving Air Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 30
    suction_temperature:
      name: "Suction Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 40
    dhw_temperature:
      name: "DHW Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 50
    fp1_temperature:
      name: "FP1 Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 60
    fp2_temperature:
      name: "FP2 Temperature"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 70
    sat_evap_temperature:
      name: "Saturated Evaporator Temp"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 80
    superheat:
      name: "Superheat"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 90
    sat_cond_temperature:
      name: "Sat Condenser Discharge Temp"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 95
    subcooling_heating:
      name: "SubCooling (Heating)"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 96
    subcooling_cooling:
      name: "SubCooling (Cooling)"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 97
    heating_liquid_line_temperature:
      name: "Heating Liquid Line Temp"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 98
    refrigerant_leaving_air_temperature:
      name: "Refrigerant Leaving Air Temp"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 99
    waterflow:
      name: "Waterflow"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 100
    discharge_pressure:
      name: "Discharge Pressure"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 110
    suction_pressure:
      name: "Suction Pressure"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 120
    loop_pressure:
      name: "Loop Pressure"
      web_server:
        sorting_group_id: group_axb_performance
        sorting_weight: 130
    # --- Power & Electrical ---
    compressor_power:
      name: "Compressor Power"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 10
    blower_power:
      name: "Blower Power"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 20
    aux_heat_power:
      name: "Aux Heat Power"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 30
    total_power:
      name: "Total Power"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 40
    pump_power:
      name: "Pump Power"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 50
    line_voltage:
      name: "Line Voltage"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 60
    compressor_amps:
      name: "Compressor Amps"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 70
    blower_amps:
      name: "Blower Amps"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 80
    aux_heat_amps:
      name: "Aux Heat Amps"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 85
    compressor_2_amps:
      name: "Compressor 2 Amps"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 86
    heat_of_extraction:
      name: "Heat of Extraction"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 90
    heat_of_rejection:
      name: "Heat of Rejection"
      web_server:
        sorting_group_id: group_power
        sorting_weight: 100
    # --- System Outputs ---
    ecm_speed:
      name: "ECM Blower Speed"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 5
    compressor_speed:
      name: "Compressor Speed"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 10
    # --- IZ2 ---
    iz2_outdoor_temperature:
      name: "IZ2 Outdoor Temperature"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 25
    iz2_demand:
      name: "IZ2 Demand"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 45
    # --- VS Drive (operational/electrical) ---
    vs_compressor_speed_requested:
      name: "VS Compressor Speed Requested"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 10
    vs_compressor_power:
      name: "VS Compressor Power"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 20
    vs_thermo_power:
      name: "VS Thermo Power"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 30
    vs_eev2_open:
      name: "VS EEV2 % Open"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 40
    vs_fan_speed:
      name: "VS Fan Speed"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 50
    vs_line_voltage:
      name: "VS Line Voltage"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 60
    vs_supply_voltage:
      name: "VS Supply Voltage"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 70
    vs_udc_voltage:
      name: "VS UDC Voltage"
      web_server:
        sorting_group_id: group_vs_drive
        sorting_weight: 80
    # --- VS Drive Sensors (temperatures & pressures) ---
    vs_drive_temperature:
      name: "VS Drive Temperature"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 10
    vs_inverter_temperature:
      name: "VS Inverter Temperature"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 20
    vs_compressor_ambient_temperature:
      name: "VS Compressor Ambient Temp"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 30
    vs_discharge_temperature:
      name: "VS Discharge Temperature"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 40
    vs_suction_temperature:
      name: "VS Suction Temperature"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 50
    vs_entering_water_temperature:
      name: "VS Entering Water Temp"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 60
    vs_sat_evap_discharge_temperature:
      name: "VS Sat Evap Discharge Temp"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 70
    vs_superheat_temperature:
      name: "VS Superheat Temperature"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 80
    vs_discharge_pressure:
      name: "VS Discharge Pressure"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 90
    vs_suction_pressure:
      name: "VS Suction Pressure"
      web_server:
        sorting_group_id: group_vs_sensors
        sorting_weight: 100
  # --- Diagnostics ---
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic
    web_server:
      sorting_group_id: group_diagnostics
      sorting_weight: 30
  - platform: wifi_signal
    name: WiFi Signal
    id: wifi_signal_db
    icon: mdi:wifi
    entity_category: diagnostic
    web_server:
      sorting_group_id: group_diagnostics
      sorting_weight: 40
  - platform: copy
    source_id: wifi_signal_db
    id: wifi_signal_pct
    name: WiFi Signal %
    icon: mdi:wifi
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    web_server:
      sorting_group_id: group_diagnostics
      sorting_weight: 50

binary_sensor:
  - platform: waterfurnace
    compressor:
      name: "Compressor"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 20
    compressor_stage2:
      name: "Compressor Stage 2"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 30
    reversing_valve:
      name: "Reversing Valve"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 40
    blower:
      name: "Blower"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 50
    aux_heat_stage1:
      name: "Aux Heat Stage 1"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 60
    aux_heat_stage2:
      name: "Aux Heat Stage 2"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 70
    lockout:
      name: "Lockout"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 80
    alarm:
      name: "Alarm"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 90
    accessory:
      name: "Accessory"
      web_server:
        sorting_group_id: group_system_outputs
        sorting_weight: 100

switch:
  - platform: waterfurnace
    dhw_enable:
      name: "DHW Enable"
      web_server:
        sorting_group_id: group_controls
        sorting_weight: 10

button:
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart
    entity_category: config
    web_server:
      sorting_group_id: group_controls
      sorting_weight: 20

text_sensor:
  - platform: waterfurnace
    current_fault:
      name: "Current Fault"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 50
    model_number:
      name: "Model Number"
      web_server:
        sorting_group_id: group_diagnostics
        sorting_weight: 10
    serial_number:
      name: "Serial Number"
      web_server:
        sorting_group_id: group_diagnostics
        sorting_weight: 20
    system_mode:
      name: "System Mode"
      web_server:
        sorting_group_id: group_thermostat
        sorting_weight: 5
    outputs_at_lockout:
      name: "Outputs at Lockout"
      web_server:
        sorting_group_id: group_diagnostics
        sorting_weight: 80
    inputs_at_lockout:
      name: "Inputs at Lockout"
      web_server:
        sorting_group_id: group_diagnostics
        sorting_weight: 90
  - platform: template
    name: Device ID
    id: device_id
    icon: mdi:identifier
    entity_category: diagnostic
    update_interval: never
    web_server:
      sorting_group_id: group_diagnostics
      sorting_weight: 60
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic
    web_server:
      sorting_group_id: group_diagnostics
      sorting_weight: 70
