substitutions:
  name: waterfurnace
  friendly_name: WaterFurnace Aurora
  component_source: github://espforge/esphome-waterfurnace@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: espforge.waterfurnace
    version: "0.0.1-beta"
  on_boot:
    priority: 800.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

preferences:
  flash_write_interval: 24h

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:

api:
  custom_services: true

ota:
  - platform: esphome
    id: ota_esphome

external_components:
  - source: ${component_source}

# RS-485 UART - Waveshare ESP32-S3-RS485-CAN board
# TX: GPIO17, RX: GPIO18, DE: GPIO21 (hardware auto-direction)
uart:
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 19200
  parity: EVEN
  rx_buffer_size: 512

waterfurnace:
  id: wf
  update_interval: 10s
  # flow_control_pin: GPIO21  # Uncomment if hardware auto-direction doesn't work
  connected:
    name: "Connected"
  connected_timeout: 30s

sensor:
  - platform: waterfurnace
    entering_water_temperature:
      name: "Entering Water Temperature"
    leaving_water_temperature:
      name: "Leaving Water Temperature"
    outdoor_temperature:
      name: "Outdoor Temperature"
    entering_air_temperature:
      name: "Entering Air Temperature"
    leaving_air_temperature:
      name: "Leaving Air Temperature"
    ambient_temperature:
      name: "Ambient Temperature"
    suction_temperature:
      name: "Suction Temperature"
    dhw_temperature:
      name: "DHW Temperature"
    discharge_pressure:
      name: "Discharge Pressure"
    suction_pressure:
      name: "Suction Pressure"
    loop_pressure:
      name: "Loop Pressure"
    waterflow:
      name: "Waterflow"
    compressor_power:
      name: "Compressor Power"
    blower_power:
      name: "Blower Power"
    aux_heat_power:
      name: "Aux Heat Power"
    total_power:
      name: "Total Power"
    pump_power:
      name: "Pump Power"
    line_voltage:
      name: "Line Voltage"
    compressor_amps:
      name: "Compressor Amps"
    blower_amps:
      name: "Blower Amps"
    relative_humidity:
      name: "Relative Humidity"
    compressor_speed:
      name: "Compressor Speed"
    heat_of_extraction:
      name: "Heat of Extraction"
    heat_of_rejection:
      name: "Heat of Rejection"
    fp1_temperature:
      name: "FP1 Temperature"
    fp2_temperature:
      name: "FP2 Temperature"
    subcooling:
      name: "Subcooling"
    superheat:
      name: "Superheat"
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic
  - platform: wifi_signal
    name: WiFi Signal
    id: wifi_signal_db
    entity_category: diagnostic
  - platform: copy
    source_id: wifi_signal_db
    id: wifi_signal_pct
    name: WiFi Signal %
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

binary_sensor:
  - platform: waterfurnace
    compressor:
      name: "Compressor"
    compressor_stage2:
      name: "Compressor Stage 2"
    reversing_valve:
      name: "Reversing Valve"
    blower:
      name: "Blower"
    aux_heat_stage1:
      name: "Aux Heat Stage 1"
    aux_heat_stage2:
      name: "Aux Heat Stage 2"
    lockout:
      name: "Lockout"
    alarm:
      name: "Alarm"
    accessory:
      name: "Accessory"

switch:
  - platform: waterfurnace
    dhw_enable:
      name: "DHW Enable"

button:
  - platform: restart
    name: Restart
    id: restart_button
    entity_category: config

text_sensor:
  - platform: waterfurnace
    current_fault:
      name: "Current Fault"
    model_number:
      name: "Model Number"
    serial_number:
      name: "Serial Number"
    system_mode:
      name: "System Mode"
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic
